name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.x
    - name: Build and test with Rake
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
        gem install bundler -v 2.1.4
        bundle install --jobs 4 --retry 3 --without production
        bundle exec rake
