name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install some deps
      run: |
        sudo apt-get install sqlite3 libsqlite3-dev
    - uses: actions/checkout@v1
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Test with Rake
      run: |
        bundle exec rake
